In [1]:
import numpy as np

In [2]:
arr=np.array([4,26,265,16,3456])

In [3]:
print(arr)

[   4   26  265   16 3456]


In [4]:
arr

array([   4,   26,  265,   16, 3456])

In [6]:
arr[1]

np.int64(26)

In [8]:
print(arr[1])

26


In [10]:
arr.shape

(5,)

In [12]:
arr.dtype

dtype('int64')

In [16]:
arr[0]=45

In [17]:
print(arr)

[  45   26  265   16 3456]


#array creation:conversion from other python structures


In [20]:
lisarray=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [21]:
lisarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
lisarray.size

9

In [24]:
lisarray.dtype

dtype('int64')

In [25]:
zerors=np.zeros((2,3))

In [27]:
zerors

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
rag=np.arange(14)

In [30]:
rag

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [31]:
lspace=np.linspace(1,13,12)

In [32]:
lspace

array([ 1.        ,  2.09090909,  3.18181818,  4.27272727,  5.36363636,
        6.45454545,  7.54545455,  8.63636364,  9.72727273, 10.81818182,
       11.90909091, 13.        ])

In [34]:
iden=np.identity(23)

In [35]:
iden

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0.,

In [36]:
iden.shape


(23, 23)

In [37]:
arr=np.arange(99)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [39]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [41]:
arr.reshape(3,32)

ValueError: cannot reshape array of size 99 into shape (3,32)

In [42]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [43]:
arr.shape

(99,)

**axis in numpy**

**axis 1=columns and axis 0=rows**

In [45]:
x=[[1,2,3],[2,3,4],[45,64,34]]

In [46]:
arr=np.array(x)

In [47]:
arr

array([[ 1,  2,  3],
       [ 2,  3,  4],
       [45, 64, 34]])

In [48]:
arr.sum(axis=0)

array([48, 69, 41])

In [49]:
arr.sum(axis=1)

array([  6,   9, 143])

**transpose of array=row becomes columns and visa versa**

In [50]:
arr.T

array([[ 1,  2, 45],
       [ 2,  3, 64],
       [ 3,  4, 34]])

In [51]:
arr.flat

In [52]:
for item in arr.flat:
    print(item)

1
2
3
2
3
4
45
64
34


In [53]:
arr.ndim

2

**argmax and argmin**

In [57]:
a = np.array([1,2,42,34,654,4453,35])

In [58]:
a.argmax()

np.int64(5)

In [59]:
a.argmin()

np.int64(0)

In [60]:
a.argsort()

array([0, 1, 3, 6, 2, 4, 5])

In [61]:
arr

array([[ 1,  2,  3],
       [ 2,  3,  4],
       [45, 64, 34]])

In [62]:
arr.argmin()

np.int64(0)

In [63]:
arr.argmax()

np.int64(7)

In [65]:
arr.ravel()

array([ 1,  2,  3,  2,  3,  4, 45, 64, 34])

**matrix operation**

In [68]:
ar1=np.array([[ 1,  2,  3],
       [ 2,  3,  4],
       [45, 64, 34]])

In [69]:
arr+ar1

array([[  2,   4,   6],
       [  4,   6,   8],
       [ 90, 128,  68]])

In [70]:
arr*ar1

array([[   1,    4,    9],
       [   4,    9,   16],
       [2025, 4096, 1156]])

In [71]:
arr/ar1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [72]:
arr-ar1

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [74]:
np.sqrt(ar1)

array([[1.        , 1.41421356, 1.73205081],
       [1.41421356, 1.73205081, 2.        ],
       [6.70820393, 8.        , 5.83095189]])

In [75]:
ar1.min()

np.int64(1)

In [76]:
ar1.max()

np.int64(64)

In [77]:
ar1.sum()

np.int64(158)